baseURL = "https://blog.kele14.com/"
languageCode = "en-us"
title = "Kele's Blog"
theme = "hugo-xmin"
uglyURLs = true

[menus]
  [[menus.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menus.main]]
    name = "About"
    url = "/about"
    weight = 2
  [[menus.main]]
    name = "Categories"
    url = "/categories"
    weight = 3
  [[menus.main]]
    name = "Tags"
    url = "/tags"
    weight = 4
  [[menus.main]]
    name = "Subscribe"
    url = "/index.xml"
    weight = 5

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
      [markup.goldmark.extensions.typographer]
        disable = true
